Vagrant.configure("2") do |config|
#  config.vm.box = "puppetlabs/centos-7.2-64-puppet"
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 1
  end   
    config.vm.box = "puppetlabs/centos-7.2-64-puppet"
    config.vm.network "private_network", ip: "192.168.56.12"
    config.vm.hostname = "pup"
  end

